# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:

name: AzureCLISample

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      #- name: Fix Template
       # uses: hashicorp/packer-github-actions@master
        #with:
         # command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: PackerWindow10Pro.pkr.hcl



      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: PackerWindow10Pro.pkr.hcl
          working_directory: '.'
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SCERET }}
